semirestfulUsers/apps/users/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'new/$', views.new,name='new'),
    url(r'(?P<id>\d+)/show$',views.show,name='show'),
    url(r'create/$', views.create,name='create'),
    url(r'(?P<id>\d+)/delete/$',views.delete,name='delete'),
    url(r'(?P<id>\d+)/edit$',views.edit,name='edit'),
    url(r'(?P<id>\d+)/update/$', views.update,name='update'),
]

semirestfulUsers/semirestfulUsers/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'users/',include('apps.users.urls',namespace='users')),
    url(r'^admin/', admin.site.urls),
]

semirestfulUsers/apps/users/models.py
from django.db import models
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class UserManager(models.Manager):
    def validator(self,postData):
        errors={}
        if len(postData['name']) < 5:
            errors['name']="Name must not be empty"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email']="Email must be valid"
        exists=User.objects.filter(email=postData['email'])
        if exists:
            errors['emailUsed']="Email is taken"
        return errors
class User(models.Model):
    name=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add= True)
    updated_at=models.DateTimeField(auto_now= True)
    objects=UserManager()

semirestfulUsers/apps/users/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from apps.users.models import *
from django.contrib import messages
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your views here.

def index(req):
    context={
        'users': User.objects.all()
    }
    return render(req,'users/index.html',context)

def new(req):
    return render(req,'users/new.html')

def show(req,id):
    user=User.objects.get(id=id)
    context={
        'user':user
    }
    return render(req,'users/show.html',context)
def delete(req,id):
    b= User.objects.get(id=id)
    b.delete()
    return redirect(f'/users/')

def edit(req,id):
    user=User.objects.get(id=id)
    context={
        'user':user
    }
    return render(req,'users/edit.html',context)
def update(req,id):
    errors= User.objects.validator(req.POST)
    if errors:
        for key,value in errors.items():
            messages.error(req,value)
        return redirect(f'/users/{id}/edit')
    else:
        user=User.objects.get(id=id)
        user.name= req.POST['name']
        user.email=req.POST['email']
        return redirect(f'/users/{id}/show')

def create(req):
    errors= User.objects.validator(req.POST)
    if errors:
        for key,value in errors.items():
            messages.error(req,value)
        return redirect(f'/users/new')

    User.objects.create(name=req.POST['name'],email=req.POST['email'])
    id=User.objects.last().id
    return redirect(f'/users/{id}/show')

semirestfulUsers/apps/users/templates/users/edit.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Edit User</title>

        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.3/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        {%if messages%}
            {%for message in messages%}
                <h3 class="error">{{message}}</h3>
            {%endfor%}
        {%endif%}
        <form action="update/" method="post">
            {%csrf_token%}
            <div class="form-group">
                <label for="name">Full Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{user.name}}">
            </div>
            <div class="form-group">
                <label for="email">email</label>
                <input type="text" class="form-control" name="email" id="email" value="{{user.email}}">
            </div>
            <input type="submit" value="Make Changes">
        </form>

        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

semirestfulUsers/apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Semi-Restful Users</title>

        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.3/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {%for user in users%}
                    <tr>
                        <td>{{user.id}}</td>
                        <td>{{user.name}}</td>
                        <td>{{user.email}}</td>
                        <td>
                            <a href="/users/{{user.id}}/show">Show  |</a>
                            <a href="/users/{{user.id}}/edit">   Edit   |</a>
                            <a href="/users/{{user.id}}/delete">   Delete</a>
                        </td>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
        <a href={%url 'users:new' %}>Create a new user</a>
        

        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

semirestfulUsers/apps/users/templates/users/new.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Semi Restful Users New</title>

        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.3/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            .error{
                color:red;
            }
        </style>
    </head>
    <body>
        {%if messages%}
            {%for message in messages%}
                <h3 class="error">{{message}}</h3>
            {%endfor%}
        {%endif%}
        <form action="create/" method="POST" role="form">
            {%csrf_token%}
            <legend>New User</legend>
            <div class="form-group">
                <label for="name">Full Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Full Name">
            </div>
            <div class="form-group">
                <label for="email">email</label>
                <input type="text" class="form-control" name="email" id="email" placeholder="Full Name">
            </div>
            <button type="submit" class="btn btn-primary">Create User</button>
        </form>
        
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

semirestfulUsers/apps/users/templates/users/show.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Show User</title>

        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.3/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="container text-center">
            <h1>User: {{user.id}} </h1>
            <h1>Full Name: {{user.name}}</h1>
            <h1>Email: {{user.email}}</h1>
            <h1>Created At: {{user.created_at}}</h1>
        </div>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>